---
version: '3'
services:
  server:
    image: rancher/k3s:v1.0.1
    command: server --disable-agent --no-deploy=servicelb --no-deploy=traefik --no-deploy=local-storage --no-deploy=metrics-server
    environment:
      - K3S_CLUSTER_SECRET=somethingtotallyrandom
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      # This is just so that we get the kubeconfig file out
      - .:/output
    ports:
      - 6443:6443

  node:
    image: rancher/k3s:v1.0.1
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
      - K3S_URL=https://server:6443
      - K3S_CLUSTER_SECRET=somethingtotallyrandom

volumes:
  k3s-server: {}
