---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demo
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: ./
    repoURL: https://github.com/hashicorp/vault-helm.git
    targetRevision: v0.3.1
    helm:
      values: |-
        server:
          dev:
            enabled: true
